//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.05 at 06:49:00 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://alisiecki.pp/internet-plans-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.alisiecki_pp.internet_plans_soap;
